#Bulldog Plugin v0.1.3 - Config-File
global-settings:
    #Hey! Add Some Stuff Here!
kits:
    bulldog:
        level-1:
            items:stone_sword,potion:16421:5,potion:16386:4
            armour:302,307,300,309
        level-2:
            items:iron_sword,potion:16421:5,potion:16386:4
            armour:306,307,308,309
        level-3:
            items:iron_sword,bow,arrow:8,potion:16421:5,potion:16386:4
            armour:306,307,308,309
        level-4:
            items:iron_sword,bow,arrow:16,potion:16421:8,potion:16386:8
            armour:310,311,312,313
        level-5:
            items:diamond_sword,bow,arrow:32, potion:16421:10,potion:16386:10,potion:8193:1
            armour:310,311,312,313
    chaser:

        level-1:
            items:wood_sword,potion:16396:5,potion:16389:3
            armour:302,303,304,305
        level-2:
            items:stone_sword,bow,arrow:8,potion:16396:5,potion:16389:6
            armour:302,307,304,309
        level-3:
            items:iron_sword,bow,arrow:32,potion:16388:2,potion:16396:10,potion:16389:6
            armour:306,307,308,309
        level-4:
            items:iron_sword,bow,arrow:64,potion:16388:7,potion:16396:10,potion:16389:6
            armour:306,307,308,309
        level-5:
            items:diamond_sword,bow,arrow:128,potion:16388:10,potion:16396:20,potion:16389:8
            armour:310,311,312,313