name: Bulldog
main: bulldog.Bulldog
version: 0.1.0
author: NeonSparked
description: This plugin recreates the game Bulldog for Minecraft Bukkit and Spigot.
database: true
depend: [WorldEdit, SQLibrary]


commands:
    bulldog:
      description: Gives Access to all Bulldog Commands
      usage: /<command>
      default: not op
      permission: bulldog.*
      permission-message: You don't have <permission> 	
    bulldogarena:
      description: Gives Access to all Bulldog Arena Commands
      usage: /<command>
      default: op
      permission: bulldog.arena.*
      permission-message: You don't have <permission>
